version: "3"

vars:
  VERSION: v0.0.1-test

tasks:
  ## ------------------------------------------------------------
  ## Node tasks
  ## ------------------------------------------------------------
  bind:
    cmds:
      - mkdir -p build
      - task: bind:android
      - task: bind:ios
      - task: bind:wasm
      - mv motorlib-android_arm64 build/motorlib-android_arm64
      - mv motorlib-ios build/motorlib-ios
      - mv motorlib-web build/motorlib-web
      - mv build ../build

  bind:android:
    dir: motor-mobile
    cmds:
      - mkdir motorlib-android_arm64
      - gomobile bind -ldflags='-s -w' -target=android/arm64 -o motorlib-android_arm64/io.sonr.motor.aar -v
      - rm -rf motorlib-android_arm64/io.sonr.motor-sources.jar
      - mv motorlib-android_arm64 ../motorlib-android_arm64

  bind:ios:
    dir: motor-mobile
    cmds:
      - mkdir motorlib-ios
      - gomobile bind -ldflags='-s -w' -target=ios -o motorlib-ios/SonrMotor.xcframework -v
      - mv motorlib-ios ../motorlib-ios

  bind:wasm:
    dir: motor-wasm
    cmds:
      - mkdir motorlib-web
      - GOOS=js GOARCH=wasm go build -tags wasm -o motorlib-web/sonr-motor.wasm -v
      - mv motorlib-web ../motorlib-web

  clean:
    cmds:
      - find ./ -type d -name "motorlib-ios_arm64" -exec rm -rf {} +
      - find ./ -type d -name "motorlib-android_arm64" -exec rm -rf {} +
      - find ./ -type d -name "build" -exec rm -rf {} +
