name: Build and Test

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  run-goreleaser:
    name: "Build All Binaries and Frameworks"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.17

      - id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23c

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"
          
      - name: Install Gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          go get golang.org/x/mobile/cmd/gobind
          go get golang.org/x/mobile/cmd/gomobile
          gomobile init
        env:
          GOPROXY: https://proxy.golang.org,direct
          GO111MODULE: "on"

      # - name: Configure Homebrew w/ cache
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/Library/Caches/Homebrew/foo--*
      #       ~/Library/Caches/Homebrew/downloads/*--foo-*
      #     key: brew-${{ hashFiles('.github/brew-formulae') }}
      #     restore-keys: brew-
      # - name: Install Homebrew dependencies
      #   run: |
      #     brew install FiloSottile/musl-cross/musl-cross
      #     brew install mingw-w64

      - name: Run coverage
        continue-on-error: true
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Prepare Release Variables
        id: vars
        uses: ignite-hq/cli/actions/release/vars@develop

      - name: Issue Release Assets
        uses: ignite-hq/cli/actions/cli@develop
        with:
          args: chain build --release --release.prefix ${{ steps.vars.outputs.tarball_prefix }} -t linux:amd64 -t darwin:amd64



      - name: Test Motor Bind
        run: make bind

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
