name: Build and Test

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:
  run-bulid:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.18, 1.19]
        ignite-version: [v0.22.1, v0.23.0, v0.24.0]
    name: "Build/Test ${{ matrix.os }}; Go ${{ matrix.go-version }}; Ignite ${{ matrix.ignite-version }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: ~${{ matrix.go-version }}

      - name: Install Ignite
        run: |
          sudo curl https://get.ignite.com/cli@${{matrix.ignite-version}}! | sudo bash

      - name: Run build against Release target for macos and linux
        continue-on-error: false
        run: |
          ignite chain build --release -t linux:amd64 -t darwin:amd64

      - name: Run tests and evaluate coverage
        continue-on-error: true
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3


  bind-them-all:
    strategy:
      matrix:
        platform: [ios, web, android]
        build-on: [ubuntu-latest, macos-latest]
        go-version: [1.17, 1.18, 1.19]
        ndk-version: [23.1.7779620]
        exclude:
        - build-on: ubuntu-latest
          platform: ios
        - build-on: macos-latest
          platform: android
      fail-fast: false
    name: "Bindings: ${{ matrix.platform }}; ${{ matrix.build-on }}; Go ${{ matrix.go-version }}"
    runs-on: ${{ matrix.build-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Force NDK version
        if : matrix.platform == 'android'
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${{ matrix.ndk-version }}" | grep -v = || true
          echo 'ANDROID_NDK=/usr/local/lib/android/sdk/ndk/${{ matrix.ndk-version }}' >> $GITHUB_ENV
          echo 'ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/${{ matrix.ndk-version }}' >> $GITHUB_ENV
          echo 'ANDROID_NDK_LATEST_HOME=/usr/local/lib/android/sdk/ndk/${{ matrix.ndk-version }}' >> $GITHUB_ENV
          echo 'ANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/${{ matrix.ndk-version }}' >> $GITHUB_ENV

      - uses: actions/setup-java@v3
        if: matrix.platform == 'android'
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"

      - uses: actions/setup-go@v3
        with:
          go-version: ~${{ matrix.go-version }}

      - name: Install Gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          go get golang.org/x/mobile/cmd/gobind
          go get golang.org/x/mobile/cmd/gomobile
          gomobile init
        env:
          GOPROXY: https://proxy.golang.org,direct
          GO111MODULE: "on"

      - name: Test Motor Bind
        run: make bind.${{ matrix.platform }}
