name: Gomobile iOS Framework Build
on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    name: Build
    runs-on: macOS-latest

    env:
      GOPATH: /Users/runner/go

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Run Tests
      run: make test

    - name: Install gomobile
      run: |
        export GO111MODULE=off
        go get golang.org/x/mobile/...
        go install golang.org/x/mobile/...
    - name: Build mobile framework for iOS
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        unset ANDROID_HOME
        unset ANDROID_NDK_HOME
        go mod vendor
        mkdir -p /Users/runner/go/src/github.com/$GITHUB_REPOSITORY/..
        cp -a . /Users/runner/go/src/github.com/$GITHUB_REPOSITORY
        export GO111MODULE=off
        make ios
