name: Core Workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the release branch
  push:
    branches: [release]

  pull_request:
    branches: [release]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Runs the `build` job
  build:
    name: Build Frameworks and Binary

    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fetch-depth: 0

      # Setup Go Enviornment
      - uses: actions/setup-go@v1
        if: startsWith(github.ref, 'refs/tags/')

      # Download and Initialize Gomobile
      - name: Setup Gomobile
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          go get golang.org/x/mobile/bind
          gomobile init

      # Create a Build Directory
      - name: Create Build Directory
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p ${{ github.workspace }}/build/ios
          mkdir -p ${{ github.workspace }}/build/android

      # Bind iOS Framework to Plugin
      - name: Bind iOS Framework
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd ${{ github.workspace }}/bind && gomobile bind -ldflags='-s -w' -v -target=ios -bundleid=io.sonr.core -o ${{ github.workspace }}/build/ios/Core.framework

      # Bind Android Framework to Plugin
      - name: Bind Android Framework
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd ${{ github.workspace }}/bind && gomobile bind -ldflags='-s -w' -v -target=android -o ${{ github.workspace }}/build/android/io.sonr.core.aar

      # Change Directory to cmd
      - name: Change Directory to cmd
        if: startsWith(github.ref, 'refs/tags/')
        run: cd ${{ github.workspace }}/cmd

      # Build Cmd with Goreleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
